config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get    '/introduce',   to: 'dashboard#introduce'
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'
  put 'users/:id/token', to: "users#token"
  resources :tournaments do
    resources :clubs, only: %i[ index new create destroy ], controller: "tournaments/clubs"
  end
  resources :matches, only: :update
  resources :dashboard, only: :index
  resources :clubs do
    resources :players, controller: "clubs/players"
    resources :users, controller: "clubs/users"
  end

  mount LetterOpenerWeb::Engine, at: '/letters' if Rails.env.development?
end

app/models/club.rb
class Club < ApplicationRecord
  include Newest
  paginates_per 10
  
  has_one_attached :avatar
  has_many :user_clubs, dependent: :destroy
  has_many :users, through: :user_clubs
  has_many :players, dependent: :destroy
  has_many :tournament_clubs, dependent: :destroy
  has_many :tournaments, through: :tournament_clubs
  has_many :home_matches, class_name: 'Match', 
                            foreign_key: 'club_one_id', dependent: :destroy
  has_many :away_matches, class_name: 'Match',
                            foreign_key: 'club_two_id', dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 100 }
  validates :avatar, dimension: { width: { min: 100, max: 2400 } },
                     content_type: [:png, :jpg, :jpeg, :gif],
                     size: { less_than: 5.megabytes,
                             message: 'is not given between size' }

  scope :valid, -> { where('players_count > 7') }

  def can_delete?
    self.tournaments.size == 0
  end
end

app/models/player.rb
class Player < ApplicationRecord
  include Newest
  paginates_per 10
  belongs_to :club, counter_cache: true

  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
  validates :name, presence: true, length: { minimum: 1, maximum: 30 }

  def send_joined_email
    PlayerMailer.with(player: self).club_joined.deliver_later
  end
end

app/controllers/clubs/players_controller.rb
module Clubs
  class PlayersController < ApplicationController
    before_action :logged_in_user
    before_action :set_club
    before_action :correct_user, only: %i[ new create edit update destroy ]
    before_action :set_player, only: %i[ edit update destroy ]

    def index
      page = params[:page] || 1
      @q = @club.players.newest.ransack(params[:q])
      @players = @q.result.page(page)
    end
  
    def new
      @player = @club.players.build
    end
  
    def create
      @player = @club.players.build(player_params)
      respond_to do |format|
        if @player.save
          @player.send_joined_email
          format.html { redirect_to club_players_url(@club), flash: { success: "Player was successfully created." } }
          format.json { render :show, status: :created, location: @player }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @player.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
    end
  
    # PATCH/PUT /palyers/1 or /palyers/1.json
    def update
      respond_to do |format|
        if @player.update(player_params)
          format.html { redirect_to club_players_url(@club), flash: { success: "Player was successfully updated." } }
          format.json { render :show, status: :ok, location: @player }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @player.errors, status: :unprocessable_entity }
        end
      end
    end
  
    
    def destroy
      @player.destroy
      respond_to do |format|
        format.html { redirect_to club_players_url(@club), flash: { success: "Player was successfully destroyed." } }
        format.json { head :no_content }
      end
    end
  
    private

      def set_club
        @club = Club.includes(:users).find(params[:club_id])
      rescue ActiveRecord::RecordNotFound
        # trả về trang root_url khi có ngoại lệ
        respond_to do |format|
          format.html { redirect_to root_url, flash: { danger: "club not found." } }
          format.json { head :not_found }
        end
      end
   
      def set_player     
        @player = @club.players.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to club_players_url(@club), flash: { danger: "player not found." } }
          format.json { head :not_found }
        end
      end
  
      # Only allow a list of trusted parameters through.
      def player_params
        params.require(:player).permit(:name, :email, :club_id)
      end

      # Confirms the correct user.
      def correct_user
        unless current_user.admin? || current_user.clubs.include?(@club)
          redirect_to dashboard_index_url, flash: { danger: "You do not have the right to access." }
        end
      end
  end    
end

app/controllers/clubs/users_controller.rb
module Clubs
  class UsersController < ApplicationController
    before_action :logged_in_user
    before_action :admin_user, only: :destroy
    before_action :set_club
    before_action :correct_user, only: %i[ new create edit update ]
    before_action :set_user, only: %i[ edit update destroy ]

    # GET /users or /users.json
    def index
      page = params[:page] || 1
      @q = @club.users.newest.ransack(params[:q])
      @users = @q.result.page(page).per(10)
    end
   
    # GET /users/new
    def new   
      @user = User.new
    end

    # POST /users or /users.json
    def create
      @user = User.create(user_params)
      if @user.valid?
        @club.users << @user
        respond_to do |format| 
          format.html { redirect_to club_users_url(@club), flash: { success: "User was successfully created." } } 
          format.json { render :show, status: :created, location: @user }
        end
      else
        respond_to do |format| 
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
    end
  
    # PATCH/PUT /users/1 or /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to club_users_url(@club), flash: { success: "User was successfully updated." } }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user.destroy
      
      respond_to do |format|
        format.html { redirect_to club_users_url(@club), flash: { success: "User was successfully destroyed." } }
        format.json { head :no_content }
      end
    end

    private
    
      def set_club
        @club = Club.includes(:users).find(params[:club_id])
      rescue ActiveRecord::RecordNotFound
        # trả về trang root_url khi có ngoại lệ
        respond_to do |format|
          format.html { redirect_to root_url, flash: { danger: "club not found." } }
          format.json { head :not_found }
        end
      end
  
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = @club.users.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to club_users_url(@club), flash: { danger: "User not found." } }
          format.json { head :not_found }
        end
      end
    
      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

      # Confirms the correct user.
      def correct_user
        unless current_user.admin? || current_user.clubs.include?(@club)
          redirect_to dashboard_index_url, flash: { danger: "You do not have the right to access." }
        end
      end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    before_action :logged_in_user
    before_action :admin_user, only: %i[ new create destroy ]
    before_action :set_club, only: %i[ edit update destroy ]
    before_action :correct_user, only: %i[ edit update ]

    # GET /clubs or /clubs.json
    def index
      page = params[:page] || 1
      @q = Club.newest.ransack(params[:q])
      @clubs = @q.result.page(page)

    end
  
    # GET /clubs/1 or /clubs/1.json
 
    # GET /clubs/new
    def new
      @club = Club.new
    end
  
    # GET /clubs/1/edit
    def edit
    end
  
    # POST /clubs or /clubs.json
    def create
      @club = Club.new(club_params)
  
      respond_to do |format|
        if @club.save
          format.html { redirect_to clubs_url, flash: { success: "Club was successfully created." } }
          format.json { render :show, status: :created, location: @club }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @club.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /clubs/1 or /clubs/1.json
    def update
      respond_to do |format|
        if @club.update(club_params) 
          format.html { redirect_to clubs_url, flash: { success: "Club was successfully updated." } }
          format.json { render :show, status: :ok, location: @club }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @club.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /clubs/1 or /clubs/1.json
    def destroy
      @club.destroy
      
      respond_to do |format|
        format.html { redirect_to clubs_url, flash: { success: "Club was successfully destroyed." } }
        format.json { head :no_content }
      end
    end
  
    private

      def set_club
        @club = Club.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to clubs_url, flash: { danger: "Club not found." } }
          format.json { head :no_content }
        end
      end
  
      def club_params
        params.require(:club).permit(:name , :avatar)
      end

      # Confirms the correct user.
      def correct_user
        unless current_user.admin? || current_user.clubs.include?(@club)
          redirect_to dashboard_index_url, flash: { danger: "You do not have the right to access." }
        end
      end
end

app/controllers/tournaments/clubs_controller.rb
module Tournaments
  class ClubsController < ApplicationController
    before_action :logged_in_user
    before_action :admin_user
    before_action :set_tournament
    before_action :valid_clubs, only: %i[ new create ]
    before_action :set_club, only: :destroy

    def index
      page = params[:page] || 1
      @clubs = @tournament.clubs.page(page).per(8)
    end

    def new
    end
  
    def create
      respond_to do |format|
        if @tournament.update(tournament_params)
          format.html { redirect_to tournament_clubs_url(@tournament), flash: { success: "Add clubs successfully." } }
          format.json { render json: { ok: true }, status: :created}
        else
          flash.now[:danger] = "Tournament has maximum 16 clubs."
          format.html { 
            render :new, status: :unprocessable_entity
          }
          format.json { head :unprocessable_entity }
        end
      end
    end

    def destroy
      @tournament.clubs.delete(@club)

      respond_to do |format|
        format.html { redirect_to tournament_clubs_path(@tournament), flash: { success: "Club was successfully destroyed." } }
        format.json { head :no_content }
      end
    end

    private

      def set_tournament
        @tournament = Tournament.find(params[:tournament_id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to root_url, flash: { danger: "Tournament not found." } }
          format.json { head :not_found }
        end
      end

      def set_club
        @club = @tournament.clubs.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to root_url, flash: { danger: "Club not found." } }
          format.json { head :not_found }
        end
      end  

      def tournament_params
        params.require(:tournament).permit(tournament_clubs_attributes: []).tap do |attrs| 
          attrs['tournament_clubs_attributes'] = attrs['tournament_clubs_attributes']
                                                 .compact_blank.map { |id| { club_id: id.to_i }.to_hash }
        end
      end

      def valid_clubs
        @options = Club.valid.reject { |club| @tournament.clubs.include?(club) }
                           .pluck(:name, :id)
      end
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/clubs/players/_form.html.erb
<div class="card p-3" style="background-color: #FAFAD2">
  <%= form_with(model: [@club, player]) do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    
    <div class="d-flex justify-content-start">
      <%= f.submit yield(:button_label), class: "btn btn-lg btn-primary mt-4" %>
    </div>
  <% end %>
</div>

app/views/clubs/players/_player.html.erb
<tr class="candidates-list">
  <td class="candidate-list-favourite-time text-center id_players">
    <%= player.id %>
  </td>
  
  <td class="title name_players">                   
    <div class="candidate-list-details">
      <div class="candidate-list-info">
        <h5 class="mb-0 text-center name_player"><%= player.name %></h5>                                           
      </div>
    </div>
  </td>

  <td class="title name_players">                   
    <div class="candidate-list-details">
      <div class="candidate-list-info">
        <h5 class="mb-0 text-center name_player"><%= player.email%></h5>                                           
      </div>
    </div>
  </td>

  <% if current_user.admin? || @club.users.include?(current_user) %>
    <td>
      <ul class="list-unstyled mb-0  justify-content-end action-list">
        <li><%= link_to 'Edit',edit_club_player_path(@club,player), class: "text-action" %>
          <i class="fas fa-edit"></i>
        </li>
        <li><%= link_to 'Destroy', [@club, player], method: :delete, data: { confirm: 'Bạn có chắc chắn muôn xóa người dùng này?' }, class: "text-action" %>
          <i class="far fa-trash-alt"></i>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/clubs/players/edit.html.erb
<% provide(:title, "#{@player.name} - Edit") %>
<% provide(:button_label, "Edit") %>
<div class="container min-vh-100">
  <div class="d-flex justify-content-center text-center mt-4">
    <h3><%= @player.name %> - Edit</h3>
  </div>
  <div class="d-flex justify-content-start mb-4">
    <%= link_to 'Back', club_players_path(@club), class: "btn btn-lg btn-secondary" %>
  </div>
  <%= render "form", player: @player %>
</div>

app/views/clubs/players/index.html.erb
<% provide(:title, "#{@club.name} - Players") %>
<div class="container min-vh-100 mt-3 mb-4">
  <h1 class="club-title">List players of club <%= @club.name %></h1>
  <div class="d-flex justify-content-between my-3">
    <%= link_to 'Back to Clubs' , clubs_path, class: "btn btn-lg btn-secondary" %>
    <% if current_user.admin? || @club.users.include?(current_user) %>
      <%= link_to 'New Player', new_club_player_path(@club) , class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>

  <div class="col-lg-12 mt-4 mt-lg-0">
    <div class="row">
      <div class="col-md-12"> 
        <div class="club-dashboard-info-box table-responsive mb-0 bg-white p-4">
          
          <table class="table table-hover manage-candidates-top mb-0">
            <thead >
              <tr>
                <th class="text-center">Id</th>
                <th class="text-center"> Name</th>
                <th class="text-center">Email</th>
                <% if current_user.admin? || @club.users.include?(current_user) %>
                  <th class="text-center">Action</th>             
                <% end %>
              </tr>
            </thead>     
              <tr class="candidates-list">
                <%= render partial: "player", collection: @players %>
              </tr>
          </table>    
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-center mt-4">     
    <%= paginate @players %>  
  </div>
</div>

app/views/clubs/players/new.html.erb
<% provide(:title, "#{@club.name} - Add player") %>
<% provide(:button_label, "Create") %>
<div class="container min-vh-100">
  <div class="d-flex justify-content-center text-center mt-4">
    <h3><%= @club.name %> - New player</h3>
  </div>
  <div class="d-flex justify-content-start mb-4">
    <%= link_to 'Back', club_players_path(@club), class: "btn btn-lg btn-secondary" %>
  </div>
  <%= render "form", player: @player %>
</div>