config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get    '/introduce',   to: 'dashboard#introduce'
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'
  put 'users/:id/token', to: "users#token"
  resources :tournaments do
    resources :clubs, only: %i[ index new create destroy ], controller: "tournaments/clubs"
  end
  resources :matches, only: :update
  resources :dashboard, only: :index
  resources :clubs do
    resources :players, controller: "clubs/players"
    resources :users, controller: "clubs/users"
  end

  mount LetterOpenerWeb::Engine, at: '/letters' if Rails.env.development?
end

app/models/club.rb
class Club < ApplicationRecord
  include Newest
  paginates_per 10
  
  has_one_attached :avatar
  has_many :user_clubs, dependent: :destroy
  has_many :users, through: :user_clubs
  has_many :players, dependent: :destroy
  has_many :tournament_clubs, dependent: :destroy
  has_many :tournaments, through: :tournament_clubs
  has_many :home_matches, class_name: 'Match', 
                            foreign_key: 'club_one_id', dependent: :destroy
  has_many :away_matches, class_name: 'Match',
                            foreign_key: 'club_two_id', dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 100 }
  validates :avatar, dimension: { width: { min: 100, max: 2400 } },
                     content_type: [:png, :jpg, :jpeg, :gif],
                     size: { less_than: 5.megabytes,
                             message: 'is not given between size' }

  scope :valid, -> { where('players_count > 7') }

  def can_delete?
    self.tournaments.size == 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Newest
  enum admin: { admin: true, normal: false }
  attr_accessor :remember_token
  before_save   :downcase_email

  has_many :user_clubs, dependent: :destroy
  has_many :clubs, through: :user_clubs
  
  validates :name, presence: true, length: { minimum: 1, maximum: 30 }
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token))
    remember_digest
  end

  # Returns a session token to prevent session hijacking.
  # We reuse the remember digest for convenience.
  def session_token
    remember_digest || remember
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update(remember_digest: nil)
  end

  private

    # Converts email to all lowercase.
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/clubs/players_controller.rb
module Clubs
  class PlayersController < ApplicationController
    before_action :logged_in_user
    before_action :set_club
    before_action :correct_user, only: %i[ new create edit update destroy ]
    before_action :set_player, only: %i[ edit update destroy ]

    def index
      page = params[:page] || 1
      @q = @club.players.newest.ransack(params[:q])
      @players = @q.result.page(page)
    end
  
    def new
      @player = @club.players.build
    end
  
    def create
      @player = @club.players.build(player_params)
      respond_to do |format|
        if @player.save
          @player.send_joined_email
          format.html { redirect_to club_players_url(@club), flash: { success: "Player was successfully created." } }
          format.json { render :show, status: :created, location: @player }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @player.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
    end
  
    # PATCH/PUT /palyers/1 or /palyers/1.json
    def update
      respond_to do |format|
        if @player.update(player_params)
          format.html { redirect_to club_players_url(@club), flash: { success: "Player was successfully updated." } }
          format.json { render :show, status: :ok, location: @player }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @player.errors, status: :unprocessable_entity }
        end
      end
    end
  
    
    def destroy
      @player.destroy
      respond_to do |format|
        format.html { redirect_to club_players_url(@club), flash: { success: "Player was successfully destroyed." } }
        format.json { head :no_content }
      end
    end
  
    private

      def set_club
        @club = Club.includes(:users).find(params[:club_id])
      rescue ActiveRecord::RecordNotFound
        # trả về trang root_url khi có ngoại lệ
        respond_to do |format|
          format.html { redirect_to root_url, flash: { danger: "club not found." } }
          format.json { head :not_found }
        end
      end
   
      def set_player     
        @player = @club.players.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to club_players_url(@club), flash: { danger: "player not found." } }
          format.json { head :not_found }
        end
      end
  
      # Only allow a list of trusted parameters through.
      def player_params
        params.require(:player).permit(:name, :email, :club_id)
      end

      # Confirms the correct user.
      def correct_user
        unless current_user.admin? || current_user.clubs.include?(@club)
          redirect_to dashboard_index_url, flash: { danger: "You do not have the right to access." }
        end
      end
  end    
end

app/controllers/clubs/users_controller.rb
module Clubs
  class UsersController < ApplicationController
    before_action :logged_in_user
    before_action :admin_user, only: :destroy
    before_action :set_club
    before_action :correct_user, only: %i[ new create edit update ]
    before_action :set_user, only: %i[ edit update destroy ]

    # GET /users or /users.json
    def index
      page = params[:page] || 1
      @q = @club.users.newest.ransack(params[:q])
      @users = @q.result.page(page).per(10)
    end
   
    # GET /users/new
    def new   
      @user = User.new
    end

    # POST /users or /users.json
    def create
      @user = User.create(user_params)
      if @user.valid?
        @club.users << @user
        respond_to do |format| 
          format.html { redirect_to club_users_url(@club), flash: { success: "User was successfully created." } } 
          format.json { render :show, status: :created, location: @user }
        end
      else
        respond_to do |format| 
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
    end
  
    # PATCH/PUT /users/1 or /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to club_users_url(@club), flash: { success: "User was successfully updated." } }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user.destroy
      
      respond_to do |format|
        format.html { redirect_to club_users_url(@club), flash: { success: "User was successfully destroyed." } }
        format.json { head :no_content }
      end
    end

    private
    
      def set_club
        @club = Club.includes(:users).find(params[:club_id])
      rescue ActiveRecord::RecordNotFound
        # trả về trang root_url khi có ngoại lệ
        respond_to do |format|
          format.html { redirect_to root_url, flash: { danger: "club not found." } }
          format.json { head :not_found }
        end
      end
  
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = @club.users.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to club_users_url(@club), flash: { danger: "User not found." } }
          format.json { head :not_found }
        end
      end
    
      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

      # Confirms the correct user.
      def correct_user
        unless current_user.admin? || current_user.clubs.include?(@club)
          redirect_to dashboard_index_url, flash: { danger: "You do not have the right to access." }
        end
      end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    before_action :logged_in_user
    before_action :admin_user, only: %i[ new create destroy ]
    before_action :set_club, only: %i[ edit update destroy ]
    before_action :correct_user, only: %i[ edit update ]

    # GET /clubs or /clubs.json
    def index
      page = params[:page] || 1
      @q = Club.newest.ransack(params[:q])
      @clubs = @q.result.page(page)

    end
  
    # GET /clubs/1 or /clubs/1.json
 
    # GET /clubs/new
    def new
      @club = Club.new
    end
  
    # GET /clubs/1/edit
    def edit
    end
  
    # POST /clubs or /clubs.json
    def create
      @club = Club.new(club_params)
  
      respond_to do |format|
        if @club.save
          format.html { redirect_to clubs_url, flash: { success: "Club was successfully created." } }
          format.json { render :show, status: :created, location: @club }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @club.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /clubs/1 or /clubs/1.json
    def update
      respond_to do |format|
        if @club.update(club_params) 
          format.html { redirect_to clubs_url, flash: { success: "Club was successfully updated." } }
          format.json { render :show, status: :ok, location: @club }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @club.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /clubs/1 or /clubs/1.json
    def destroy
      @club.destroy
      
      respond_to do |format|
        format.html { redirect_to clubs_url, flash: { success: "Club was successfully destroyed." } }
        format.json { head :no_content }
      end
    end
  
    private

      def set_club
        @club = Club.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to clubs_url, flash: { danger: "Club not found." } }
          format.json { head :no_content }
        end
      end
  
      def club_params
        params.require(:club).permit(:name , :avatar)
      end

      # Confirms the correct user.
      def correct_user
        unless current_user.admin? || current_user.clubs.include?(@club)
          redirect_to dashboard_index_url, flash: { danger: "You do not have the right to access." }
        end
      end
end

app/controllers/tournaments/clubs_controller.rb
module Tournaments
  class ClubsController < ApplicationController
    before_action :logged_in_user
    before_action :admin_user
    before_action :set_tournament
    before_action :valid_clubs, only: %i[ new create ]
    before_action :set_club, only: :destroy

    def index
      page = params[:page] || 1
      @clubs = @tournament.clubs.page(page).per(8)
    end

    def new
    end
  
    def create
      respond_to do |format|
        if @tournament.update(tournament_params)
          format.html { redirect_to tournament_clubs_url(@tournament), flash: { success: "Add clubs successfully." } }
          format.json { render json: { ok: true }, status: :created}
        else
          flash.now[:danger] = "Tournament has maximum 16 clubs."
          format.html { 
            render :new, status: :unprocessable_entity
          }
          format.json { head :unprocessable_entity }
        end
      end
    end

    def destroy
      @tournament.clubs.delete(@club)

      respond_to do |format|
        format.html { redirect_to tournament_clubs_path(@tournament), flash: { success: "Club was successfully destroyed." } }
        format.json { head :no_content }
      end
    end

    private

      def set_tournament
        @tournament = Tournament.find(params[:tournament_id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to root_url, flash: { danger: "Tournament not found." } }
          format.json { head :not_found }
        end
      end

      def set_club
        @club = @tournament.clubs.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.html { redirect_to root_url, flash: { danger: "Club not found." } }
          format.json { head :not_found }
        end
      end  

      def tournament_params
        params.require(:tournament).permit(tournament_clubs_attributes: []).tap do |attrs| 
          attrs['tournament_clubs_attributes'] = attrs['tournament_clubs_attributes']
                                                 .compact_blank.map { |id| { club_id: id.to_i }.to_hash }
        end
      end

      def valid_clubs
        @options = Club.valid.reject { |club| @tournament.clubs.include?(club) }
                           .pluck(:name, :id)
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :token
  before_action :get_user, only: :token

  def token
    if @user.update(token_param)
      render json: { ok: true }, status: :ok
    else
      render json: { ok: false }, status: :unprocessable_entity
    end
  end

  private

    def get_user
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.html { redirect_to root_url, flash: { danger: "User not found." } }
        format.json { head :not_found }
      end
    end

    def token_param
      params.require(:user).permit(:token)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clubs/users/_form.html.erb
<div class="card p-3" style="background-color: #FAFAD2">
  <%= form_with(model: [@club, user]) do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
      
    <div class="mb-3">
      <%= f.label :password_confirmation %> 
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    
    <div class="d-flex justify-content-start">
      <%= f.submit yield(:button_label), class: "btn btn-lg btn-primary mt-4" %>
    </div>
  <% end %>
</div>

app/views/clubs/users/_user.html.erb
<tr class="candidates-list">
  <td class="candidate-list-favourite-time text-center id_clubs">
    <%= user.id %>
  </td>
  
  <td class="title name_clubs">                   
    <div class="candidate-list-details">
      <div class="candidate-list-info">
        <h5 class="mb-0 text-center name_club"><%= user.name %></h5>                                           
      </div>
    </div>
  </td>

  <td class="title name_clubs">                   
    <div class="candidate-list-details">
      <div class="candidate-list-info">
        <h5 class="mb-0 text-center name_club"><%= user.email%></h5>                                           
      </div>
    </div>
  </td>

  <td>
    <ul class="list-unstyled mb-0  justify-content-end action-list">
      <% if current_user.admin? || @club.users.include?(current_user) %>
        <li><%= link_to 'Edit', edit_club_user_path(@club,user), class: "text-action" %>
          <i class="fas fa-edit"></i>
        </li>
      <% end %>
      <% if current_user.admin? %>
        <li>
          <%= link_to 'Destroy', club_user_path(@club, user), method: :delete, 
                                data: { confirm: 'Bạn có chắc chắn muôn xóa người dùng này?' },
                                class: "text-action" %>
            <i class="far fa-trash-alt"></i>
        </li>
      <% end %>
    </ul>
  </td>
</tr>

app/views/clubs/users/edit.html.erb
<% provide(:title, "#{@user.name} - Edit") %>
<% provide(:button_label, "Edit") %>
<div class="container min-vh-100">
  <div class="d-flex justify-content-center text-center mt-4">
    <h3><%= @user.name %> - Edit</h3>
  </div>
  <div class="d-flex justify-content-start mb-4">
    <%= link_to 'Back', club_users_path(@club), class: "btn btn-lg btn-secondary" %>
  </div>
  <%= render "form", user: @user %>
</div>

app/views/clubs/users/index.html.erb
<% provide(:title, "#{@club.name} - Users List") %>
<div class="container min-vh-100 mt-3 mb-4">
  <h1 class="club-title">List user of clubs <%= @club.name%></h1>
  
  <div class="d-flex justify-content-between mb-3">
    <%= link_to 'Back to Clubs' , clubs_path, class: "btn btn-lg btn-secondary" %>
    <% if current_user.admin? || @club.users.include?(current_user) %>
      <%= link_to 'New Users' , new_club_user_path , class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>

  <div class="col-lg-12 mt-4 mt-lg-0">
    <div class="row">
      <div class="col-md-12"> 
        <div class="club-dashboard-info-box table-responsive mb-0 bg-white p-4">
          <table class="table table-hover manage-candidates-top mb-0">
            <thead >
              <tr>
                <th class="text-center">Id</th>
                <th class="text-center"> Name</th>
                <th class="text-center">Email</th>
                <% if current_user.admin? || @club.users.include?(current_user) %>
                  <th class="action-list">Action</th>
                <% end %>
              </tr>
            </thead>

            <%= render @users %>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-center mt-4">     
    <%= paginate @users %>  
  </div>
</div>

app/views/clubs/users/new.html.erb
<% provide(:title, "New user of club #{@club.name}") %>
<% provide(:button_label, "Create") %>
<div class="container min-vh-100">
  <div class="d-flex justify-content-center text-center mt-4">
    <h3><%= @club.name %> - New user</h3>
  </div>
  <div class="d-flex justify-content-start mb-4">
    <%= link_to 'Back', club_users_path(@club), class: "btn btn-lg btn-secondary" %>
  </div>
  <%= render "form", user: @user %>
</div>