config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get    '/introduce',   to: 'dashboard#introduce'
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'
  put 'users/:id/token', to: "users#token"
  resources :tournaments do
    resources :clubs, only: %i[ index new create destroy ], controller: "tournaments/clubs"
  end
  resources :matches, only: :update
  resources :dashboard, only: :index
  resources :clubs do
    resources :players, controller: "clubs/players"
    resources :users, controller: "clubs/users"
  end

  mount LetterOpenerWeb::Engine, at: '/letters' if Rails.env.development?
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark mt-4">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4 mb-md-0 text-center">
        <h5 class="text-uppercase text-light">About</h5>
        <ul class="list-unstyled mb-0">
          <li>
            <%= link_to "Introduce", introduce_path, class: "text-light", target: "_blank" %>          
          </li>
          <li>
            <%= link_to "Contract", "#", class: "text-light" %>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4 mb-md-0 text-center">
        <h5 class="text-uppercase text-light">Policy</h5>

        <ul class="list-unstyled  mb-0">
          <li>
            <%= link_to "Privacy", "#", class: "text-light" %>
          </li>
          <li>
            <%= link_to "Payment", "#", class: "text-light" %>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4 mb-md-0 text-center">
        <h5 class="text-uppercase text-light">Product</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <%= link_to "Leagues", tournaments_path, class: "text-light" %>
          </li>
          <li>
            <%= link_to "Clubs", clubs_path, class: "text-light" %>
          </li>
        </ul>
      </div>
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 text-light" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <%= link_to "cowell-league.com", "#", class: "text-light" %>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to dashboard_index_path, class: "navbar-brand" do %>
      <%= image_tag image_url("logo.jpg"), width: "64" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Clubs", clubs_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, method: :delete, class: "nav-link", remote: true %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="card-body list-group-item-<%= key.to_s %> my-3" role="message">
    <a data-dismiss="message" href="#">
      <i class="fa fa-times me-2"></i>
    </a>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %> 
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
<script src="https://www.gstatic.com/firebasejs/9.2.0/firebase-app-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.2.0/firebase-messaging-compat.js"></script>
<link href="/manifest.json" rel="manifest" />
<%= javascript_pack_tag 'firebase', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]> 
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script>
<![endif]-->>

app/views/layouts/_toast.html.erb
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
  <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="10000">
    <div class="toast-header bg-warning text-dark">
      <strong class="me-auto" id="toast-title">Bootstrap</strong>
      <small id="toast-time">1 mins ago</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body" id="toast-body">
      Hello, world! This is a toast message.
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag "favicon.ico" %>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container-fluid px-0">
      <div class="container-fluid">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>

      <%= render "layouts/messages" %>
      <%= render "layouts/toast" %>

			<%= yield %>

      <% if logged_in? %>
        <script type="text/javascript">
          connectFirebase(<%= current_user.id %>);
        </script>
      <% end %>
    </div>
    <%# <%= render 'layouts/footer' %> %>
  </body>
</html>